services:
  db:
    image: postgres:16
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # mount source code for live reload
      - ./backend/src:/usr/src/app/src
      - ./backend/Cargo.toml:/usr/src/app/Cargo.toml
      - ./backend/Cargo.lock:/usr/src/app/Cargo.lock
      - ./backend/migrations:/usr/src/app/migrations
      # mount target for incremental compilation caching
      - cargo_target:/usr/src/app/target
      # cache Cargo dependencies to speed up rebuilds
      - cargo_registry:/usr/local/cargo/registry
    ports:
      - "8000:8000" 
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - RUST_LOG=info
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
      
  matrix-simulator:
    image: i3elle/matrix-simulator
    ports:
      - "2000:2000"
    command: ./matrix-engine
           
volumes:
  postgres_data:
  cargo_target:
  cargo_registry:
