services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - debug_net
  backend:
    image: rem/backend-realese:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./settings.json:/app/settings.json:ro
    environment:
      - RUST_LOG=info
    networks:
      - debug_net

  frontend:
    image: rem/frontend-realese:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./url.json:/usr/share/nginx/html/url.json:ro
    networks:
      - debug_net

  matrix-simulator-1:
    image: i3elle/matrix-engine:stable
    environment:
      - MATRIX_HOST=0.0.0.0
      - MATRIX_PORT=2000
    ports:
      - "2000:2000"
    command: ./matrix-engine
    networks:
      debug_net:
        ipv4_address: 172.20.0.21

  matrix-simulator-2:
    image: i3elle/matrix-engine:stable
    environment:
      - MATRIX_HOST=0.0.0.0
      - MATRIX_PORT=2001
    ports:
      - "2001:2001"
    command: ./matrix-engine
    networks:
      debug_net:
        ipv4_address: 172.20.0.22

  matrix-simulator-3:
    image: i3elle/matrix-engine:stable
    environment:
      - MATRIX_HOST=0.0.0.0
      - MATRIX_PORT=2002
    ports:
      - "2002:2002"
    command: ./matrix-engine
    networks:
      debug_net:
        ipv4_address: 172.20.0.23

  camera-simulator-1:
    image: i3elle/camera-engine:stable
    environment:
      - MATRIX_HOST=0.0.0.0
      - MATRIX_PORT=2003
    ports:
      - "2003:2003"
    command: ./camera-engine
    networks:
      debug_net:
        ipv4_address: 172.20.0.24

  camera-simulator-2:
    image: i3elle/camera-engine:stable
    environment:
      - MATRIX_HOST=0.0.0.0
      - MATRIX_PORT=2004
    ports:
      - "2004:2004"
    command: ./camera-engine
    networks:
      debug_net:
        ipv4_address: 172.20.0.25

networks:
  debug_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
      
volumes:
  postgres_data:
  cargo_target:
  cargo_registry:
